name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/ci-cd.yml"

  workflow_dispatch:

jobs:
  docker:
    name: Build and publish backend
    uses: nesco-devops/Action3/.github/workflows/docker-build-push.yml@main

    with:
      image_name: appgestion-backend
      build_context: ./backend
      dockerfile: ./backend/Dockerfile
      gitops_manifest: backend/deployment.yaml

    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
